# .travis.yml for sisposto

language: python

python:
  - "2.7"
# pylibmc does not work on python3
#  - "3.4"

install:
  - "bash venv-debian-install.sh"
  - "pip install -r requirements-test.txt"
  - "pip install coveralls"

script:
  coverage run --source=sisposto sisposto/manage.py test

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: never
