# .travis.yml for sisposto

language: python

python:
  - "2.7"
  - "3.4"

install:
  - "bash venv-debian-install.sh"
  - "pip install -r requirements-test.txt"

script:
  python sisposto/manage.py test

after_success:
  pip install --quiet coveralls
  coveralls

notifications:
  email:
    on_success: never
    on_failure: never
